# Generated by Django 4.0.6 on 2022-08-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
